
# HTTP服务启动端口
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 1003
    driver-class-name: com.mysql.cj.jdbc.Driver